2019-05-31 10:48:49,978 ERROR: Exception on /login [POST] [in /Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/digitalislands/Projects/microblog/app/routes.py", line 40, in login
    if user is None or not user.check_password(form.password.data):
  File "/Users/digitalislands/Projects/microblog/app/models.py", line 34, in check_password
    return check_password_hash(self.password_hash, password)
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/werkzeug/security.py", line 218, in check_password_hash
    if pwhash.count("$") < 2:
AttributeError: 'NoneType' object has no attribute 'count'
2019-05-31 10:48:58,075 ERROR: Exception on /login [POST] [in /Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/digitalislands/Projects/microblog/app/routes.py", line 40, in login
    if user is None or not user.check_password(form.password.data):
  File "/Users/digitalislands/Projects/microblog/app/models.py", line 34, in check_password
    return check_password_hash(self.password_hash, password)
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/werkzeug/security.py", line 218, in check_password_hash
    if pwhash.count("$") < 2:
AttributeError: 'NoneType' object has no attribute 'count'
2019-05-31 10:49:03,466 ERROR: Exception on /login [POST] [in /Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/digitalislands/Projects/microblog/app/routes.py", line 40, in login
    if user is None or not user.check_password(form.password.data):
  File "/Users/digitalislands/Projects/microblog/app/models.py", line 34, in check_password
    return check_password_hash(self.password_hash, password)
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/werkzeug/security.py", line 218, in check_password_hash
    if pwhash.count("$") < 2:
AttributeError: 'NoneType' object has no attribute 'count'
2019-05-31 11:04:05,095 INFO: Microblog startup [in /Users/digitalislands/Projects/microblog/app/__init__.py:45]
2019-05-31 11:04:08,032 ERROR: Exception on /explore [GET] [in /Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/digitalislands/Projects/microblog/app/routes.py", line 137, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/digitalislands/Projects/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/digitalislands/Projects/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/digitalislands/Projects/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/digitalislands/Projects/microblog/app/templates/index.html", line 18, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
